version: '3'
services:
  postgres:
    image: mdillon/postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD:  postgres
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/